### ISSUE TITLE
Better description for filter/4 in README for dash/snake case?

### ISSUE THREAD

**Issue by johnmosesman** [vt-elixir/ja_resource#38]
Hello again!

I figured this out through experimentation, but for clarity do you think in the filter section of the README there should be something describing the dash-to-underscore transition?

For example I set up my filter function like this:

http://localhost:4000/api/posts?filter[user-id]=1

```
def filter(_conn, query, "user-id", user_id) do
  where(query, user_id: ^user_id)              
end                                                      
```

And it wasn't being called. Didn't realize "user-id" was "user_id" when it hit `filter/4`.

If you disagree feel free to close!

**Comment by alanpeabody** [comment]
Sure, to be clear all param keys are formatted by JaSerializer in the manner you have configured (by default this is expecting dashes to be converted to underscores).

An Update to the README would be most welcome!
