### ISSUE TITLE
Using ja_resource with has_many

### ISSUE THREAD

**Issue by joshuataylor** [vt-elixir/ja_resource#45]
So I have a schema with a has_many, and passing that information through with `relationships` in a JSON API Resource produces the following with ja_resource:

```
%{"foo_ids" => [1,2,3,4]}
```

Now this is fine, but is there a "standard" way to process this in a changeset, or do I have to write this myself in each schemas changeset?

We should also add this to the docs.

**Comment by joshuataylor** [comment]
Here's the workaround I ended up doing:

```
      def process_has_many(struct, params, schema, field, key) do
        case Map.has_key?(params, key) do
          true ->
            results = schema |> where([p], p.id in ^params[key]) |> Repo.all
            struct |> Ecto.Changeset.put_assoc(field, results)
          false ->
            struct
        end
      end
```

And then in my changeset:

```
|> process_has_many(params, Post, :posts, "post_ids")
```

**Comment by alanpeabody** [comment]
You will have to handle this yourself as you did above or some other way. ✔️

**Comment by emwalker** [comment]
@alanpeabody is there any plan to support the JSON API spec for modifying relationships?

http://jsonapi.org/format/#crud-updating-relationships

**Comment by alanpeabody** [comment]
Not currently... It actually isn't a feature I have ever used.
