### ISSUE TITLE
Since elixir 1.4, compiler throws out warning for calling functions without parentheses

### ISSUE THREAD

**Issue by begedin** [vt-elixir/ja_resource#49]
See issue title.

A simple option would be to find a way to turn off those warnings.

However, since the library uses `__using__` macros to modify consuming app modules, this isn't really an option. I believe "parenthesesless" calls should simply be replaced.

**Comment by snewcomer** [comment]
This issue is fixed, correct?

**Comment by alanpeabody** [comment]
This should be fixed in the most recent build. If not please reopen with details!
