### ISSUE TITLE
Use JaSerializer.ParamParser

### ISSUE THREAD

**Issue by lubien** [vt-elixir/ja_resource#51]
JaSerializer can custom how params are parsed. It's useful if you want to post to your API in another format like camelCase.

See:
https://github.com/vt-elixir/ja_serializer/blob/master/test/ja_serializer/param_parser_test.exs

**Comment by alanpeabody** [comment]
@lubien it should be used, you need to fully install JaSerializer plugs as described in that readme.

**Comment by lubien** [comment]
Thanks
