### ISSUE TITLE
dasherized to underscore key format

### ISSUE THREAD

**Issue by atomkirk** [vt-elixir/ja_resource#60]
I'm sending this:

```
{
  "data": {
    "type": "recommendation",
    "attributes": {
      "type-id": "…",
      "status": "completed"
    }
  }
}
```

Ja serializer automatically converts my snakecase attribute names to dasherized when serializing, but it appears jaresource is not converting my POST attributes from dasherized to underscore before passing them to `permitted_attributes` or `handle_create`. I expected it to. Should I have expected that?

Specifically, `type-id` is still `type-id` in `attrs` passed to `permitted_attributes`

**Comment by psteininger** [comment]
I see that as well @atomkirk. I think the dashes should be turned back into underscores. I'll share what I find. If you have a solutions, please share it here

**Comment by psteininger** [comment]
it looks like nothing is being done about the params on the way in:
```elixir
# lib/ja_resource/attributes.ex
 def from_params(%{"data" => data}) do
    attrs = data["attributes"] || %{}

    data
    |> parse_relationships
    |> Map.merge(attrs)
    |> Map.put_new("type", data["type"])
  end
```

or here: 
```elixir
# lib/ja_resource/update.ex
def call(controller, conn) do
    model      = controller.record(conn, conn.params["id"])
    merged     = JaResource.Attributes.from_params(conn.params)
    attributes = controller.permitted_attributes(conn, merged, :update)

    conn
    |> controller.handle_update(model, attributes)
    |> JaResource.Update.update(controller)
    |> JaResource.Update.respond(conn)
  end
```

**Comment by psteininger** [comment]
@atomkirk I think the least invasive and fastest way of getting it done (without update to ja_resource) is to use `permitted_attributes` hook and convert `-` to `_`. It's a bit hacky but I think it might do the job

**Comment by psteininger** [comment]
@atomkirk here's a quick-and-dirty workaround:
```elixir
  def permitted_attributes(conn, attrs, :create) do
    attrs
    |> base_permitted_attributes
  end

  def permitted_attributes(_conn, attrs, :update) do
    attrs
    |> base_permitted_attributes
  end

  def base_permitted_attributes(attrs) do
    attrs |> Enum.reduce(%{}, fn({key, value}, acc) -> acc |> Map.put(String.replace(key, "-", "_"), value) end )
  end
```

**Comment by alanpeabody** [comment]
@psteininger you still have to install ja_serializer fully:

```elixir
pipeline :api do
  plug :accepts, ["json-api"]
  plug JaSerializer.ContentTypeNegotiation
  plug JaSerializer.Deserializer # This guy changes - to _
end
```

**Comment by psteininger** [comment]
now it makes sense @alanpeabody. I thought the deserializer was for the responses. 
Thanks so much for clearing this up. And thanks a ton for this wonderful package as well as ja_serializer. I don't think there is anything more pleasant, elegant and complete for JSON-API in any language I have worked in (PHP, Java, Ruby, Elixir).

Thank you and every contributor :)
