### ISSUE TITLE
How to kick off a job?

### ISSUE THREAD

**Issue by nathanl** [vt-elixir/ja_resource#63]
I'm using `ja_resource` in a controller, and the default behavior for updating and rendering works fine.

However, I also want to kick off a `Task.async` for `create`, `update` and `delete` requests, which will update some caches elsewhere in the system.

Any suggestions on how to hook this in?

**Comment by alanpeabody** [comment]
@nathanl I haven't had a chance to try this with Phoenix 1.3 yet, but I would look at either some type of function in a context module or similar.

Eg, for create:

```elixir
def handle_create(conn, attributes) do
  MyContextModule.create_thing(attributes)
end
```

The return values handled are documented in the callbacks: https://hexdocs.pm/ja_resource/0.3.0/JaResource.Create.html#c:handle_create/2

**Comment by nathanl** [comment]
Yep - that works. Actually, looking at the source code in `deps` really helped me understand what to do. It's very clear code! 👍
