### ISSUE TITLE
Elixir 1.6 emits compiler warnings for repeated behaviour definitions

### ISSUE THREAD

**Issue by novaugust** [vt-elixir/ja_resource#73]
We have compiler warnings set to error, so this is holding us back from adopting 1.6.

In 1.6, the compiler now warns if two behaviours declare the same callback. Further, it does not care if the two declared behaviours are, in fact, the same behaviour.

[This is not considered a bug with Elixir](https://github.com/elixir-lang/elixir/issues/7008#issuecomment-358505127).

Within jaresource, this means the repeated `use JaResource.Records` and `use JaResource.Repo` stanzas are throwing out errors. Easiest / quickest thing I could think of: reimplement those `__using__` functions to track whether they've already run within a module

**Comment by alanpeabody** [comment]
Thanks for the report @novaugust.

I don't know when I might have a chance to look at this, so in the meantime a PR from anybody to address this would be very welcome!

**Comment by novaugust** [comment]
Further discussions in that thread on elixir show that this _is_ actually a bug, yay. Can hope for a quick fix in 1.6.1 if we don't figure it out on jaresource first =)

**Comment by halfdan** [comment]
@novaugust I don't read this as Jose marking it as a bug - rather just saying it should be documented in the CHANGELOG.

**Comment by novaugust** [comment]
> @novaugust I don't read this as Jose marking it as a bug - rather just saying it should be documented in the CHANGELOG.

Yeah, he changed his mind when he realized it was a new thing from 1.5
