### ISSUE TITLE
Renewed Maintenance and feature development

### ISSUE THREAD

**Issue by psteininger** [vt-elixir/ja_resource#77]
@alanpeabody @beerlington  Would you consider accepting some help to maintain and evolve ja_resources? I found this package quite useful, especially while working with EmberJS on the frontend. I would love to contribute some features and invest some time in triaging issues and reviewing PRs. There hasn't been much movement here since at least January, so I am guessing you guys have moved one to other work and don't really use this library.

So I am offering my time to work the issues, the code and engage people to use and contribute.

Please let me know

Best,

Piotr
LaborVoices CTO

**Comment by beerlington** [comment]
🥇
