### ISSUE TITLE
Setting up relationship links

### ISSUE THREAD

**Issue by tycoles** [vt-elixir/ja_resource#84]
What convention do you guys typically use for setting up your nested relationship routes? Is there an automated way with which to do that?

Something so that these types of links work:

"links": {
"self": "/tours/3/relationships/locations",
"related": "/tours/3/locations"
}

**Comment by ericdude4** [comment]
@tycoles Do you mean in your router/controller which responds to those links, or in the serializer that makes those links?

**Comment by psteininger** [comment]
@tycoles I use this lib with Ember on the frontend. The Ember community  recommends avoiding nesting resource routes on the backend and use `?filter[..]=...` to retrieve related stuff, instead.
